### ISSUE TITLE
Mrs sophia l. Jackson

### ISSUE THREAD

**Issue by Sophiawatts** [plaid/pattern-account-funding#34]
https://github.com/plaid/pattern-account-funding/blob/9387717ffecd08b0aa1891c29a1d7930317fb3da/server/routes/items.js#L81-L135

**Comment by Sophiawatts** [comment]
Why I can't get my investments money

**Comment by phoenixy1** [comment]
Hi! These forums are for Plaid developers -- if you are having trouble with a Plaid-powered app, please contact the company that makes the app directly.

**Comment by Sophiawatts** [comment]
Yes I am how u get in touch with them
