### ISSUE TITLE
SOFTWARE DEVELOPMENT 

### ISSUE THREAD

**Issue by EleazarSosaJR13** [plaid/pattern-account-funding#45]
WHAT IS THE CRITERIA TO ATTAIN SOFTWARE DEVELOPMENT  ACCESS? WHO GRANTS ACCESS? WHAT IS A.I? SINCE WHEN HAS THIS FREE ACCESS CODING PLATFORM EXISTED? WHO HIRES DEVELOPERS? WHAT ARE THE TASKS? WHAT ARE THE PROBLEMS? AND ALL WARRANT APPROVALS AGAINST ELEAZAR SOSA ALSO KNOWN AS JUNIOR ARE COUNTERSIGNED BY THE AUDIT. IF YOU DONT SEE THE PROBLEM YOU DONT BELONG IN THE DEVELOPMENT SOFTWARE EXPERIMENT. THATS ALL THIS WAS. EXPERIMENTATION TO SEE IF YOU CAN BE TRUSTED AND ALL FAILED. NOW AMA TAKE WHAT I NEED, NOT TOO MUCH, JUST ENOUGH, BUT I HAVE NOT FIGURED OUT HOW TO PAY MYSELF.

**Comment by ToddKerpelman** [comment]
Closing as duplicate
